[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:scheduler]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
user=app
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
